// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using HMS.Entites.Enums;

namespace HMS.Entities.Models;

public class Appointment
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    public string PatientId { get; set; }

    public string StaffId { get; set; }

    public int DepartmentId { get; set; }

    public DateTime AppointmentDateTime { get; set; }

    public AppointmentStatus Status { get; set; }
  
    //Navigation Properties
    public virtual Patient? Patient { get; set; }

    public virtual Staff? Staff { get; set; }

    public virtual Department? Department { get; set; }

    public virtual MedicalHistory? MedicalHistory { get; set; }


}