// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace HMS.Entities.Models;

public partial class Department
{
    public int Id { get; set; }

    [Display(Name = "Department Name")]
    [Required]
    //[UniqueDepartmentName]
    public string Name { get; set; }

    public bool IsDeleted { get; set; }=false;  


    public virtual ICollection<Staff>? Staff { get; set; } = new List<Staff>();

    public virtual ICollection<Appointment>? Appointments { get; set; } = new List<Appointment>();
}