// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable


using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HMS.Entities.Models;

public class MedicalHistory
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    [ForeignKey(nameof(Appointment))]
    public int AppointmentId { get; set; }

    [MaxLength(500, ErrorMessage = "Diagnosis can not exceed 500 characters")]
    [Required(ErrorMessage = "Diagnosis is required.")]
    public string Diagnosis { get; set; }
    [MaxLength(1000,ErrorMessage = "Treatment plan cannot exceed 1000 characters.")]
    [Required(ErrorMessage = "Treatment plan is required.")]
    public string TreatmentPlan { get; set; }
    [MaxLength(500,ErrorMessage = "Prescription can not exceed 500 characters")]
    public string Prescription { get; set; }

    //Navigation Property 
    public virtual Appointment? Appointment { get; set; }


}