// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using HMS.Entites.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace HMS.Entities.Models;

public partial class Patient
{
    public int Id { get; set; }

    public string Address { get; set; }

    public DateOnly Dob { get; set; }

    public string EmergencyContact { get; set; }

    public string InsuranceProvider { get; set; }

    public string InsuranceNumber { get; set; }

    
    [ForeignKey(nameof(User))]
    public string UserId { get; set; }

    public virtual ICollection<Appointment>? Appointments { get; set; } = new List<Appointment>();

    public virtual ICollection<MedicalHistory>? MedicalHistories { get; set; } = new List<MedicalHistory>();
    public virtual ApplicationUser? User { get; set; }

}