// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HMS.Entities.Models;

public class StaffSchedule
{

    [Required]
    public int ScheduleId { get; set; }

    [Required]
    //[UniqueStaffSchedule]
    public string StaffId { get; set; }
    public bool IsDeleted { get; set; }

    public virtual Schedule? Schedule { get; set; }

    public virtual Staff? Staff { get; set; }
}